"""Generates data/clues.json — the clue board entries. Edit here, not the JSON."""
import json, os
C = {}
def clue(cid, title, desc, source, imp=1, rel=()):
    C[cid] = {"title": title, "desc": desc, "source": source, "importance": imp, "related": list(rel)}

# --- o número e a Inês ---------------------------------------------------
clue("photo_window", "A fotografia da janela", "Uma fotografia de ti, no sofá, tirada da rua. Às 23:44 — três minutos antes da primeira mensagem.", "Galeria · IMG_6612", 2, ["photo_window_meta", "street_watcher", "hooded_man"])
clue("photo_window_meta", "Dispositivo: desconhecido", "A metadata da fotografia da janela não identifica a câmara. O teu telemóvel não reconhece o dispositivo que a tirou.", "Galeria · detalhes de IMG_6612", 1, ["photo_window", "photo_from_behind"])
clue("door_from_inside", "A porta, de dentro", "A porta do teu quarto, fotografada de dentro do quarto, às 03:02. Enquanto dormias.", "Galeria · IMG_6630", 2, ["photo_window", "sleeping_photo"])
clue("voicemail_sea", "O mar no correio de voz", "41 segundos de mar e uma respiração muito perto do microfone. Deixado às 03:18.", "Correio de voz", 1, ["call_from_dead", "ines_he_is_coming"])
clue("unknown_mentions_book", "\"Deixa o Ricardo Reis onde está\"", "O número sabia que a Carla te pediu para arrumar os Saramagos. E pediu-te para não mexeres no livro do Ricardo Reis. \"Ainda não.\"", "Mensagens", 2, ["carla_book_moved", "saramago_spine", "daniel_hides_in_books"])
clue("pedro_ai_theory", "Teoria do Pedro: montagens com IA", "Golpes com fotografias geradas por IA a partir de redes sociais. Mas tu não tens redes sociais.", "Grupo \"Os do costume\"", 1, ["photo_window"])
clue("hooded_man", "Alguém de capuz na tua rua", "O João viu alguém de capuz parado em frente à tua casa às 2h20. Quando o viu, foi em direção ao cais.", "Mensagens · João", 1, ["street_watcher", "photo_window"])
clue("sofia_suspects_lumen", "A Sofia desconfia da Lumen", "\"Eles nunca te deixaram em paz desde aquilo. Aquele Vasco liga-te todos os meses.\"", "Mensagens · Sofia", 1, ["vasco_monitors_phone"])
clue("call_voice_woman", "Uma voz de mulher", "Na primeira chamada, uma mulher sussurrou: \"Não deixes a Carla mexer no livro.\"", "Chamada · 15:05", 2, ["unknown_mentions_book", "call_from_dead"])
clue("vasco_monitors_phone", "O Vasco vê o teu telemóvel", "O Vasco sabia do consumo de bateria do teu telemóvel. \"Gestão de dispositivos\".", "Mensagens · Vasco", 2, ["eco_care_mention", "saw_eco_battery_dummy"] )
clue("carla_book_moved", "O amuleto fora do sítio", "A Carla notou que o \"Ano da Morte de Ricardo Reis\" estava fora do sítio. Tu não mexeste nele. Pois não?", "Mensagens · Carla", 1, ["unknown_mentions_book", "saramago_spine"])
clue("street_watcher", "Debaixo do candeeiro", "Uma pessoa parada debaixo do candeeiro, a olhar para a tua janela. Às 21:58.", "Galeria · IMG_6641", 2, ["hooded_man", "photo_window"])
clue("door_was_open", "A porta estava aberta", "Quando chegaste a casa com o João, a porta estava aberta. Tens a certeza de que a fechaste?", "Mensagens · João", 1, ["street_watcher"])
clue("unknown_mentions_pier", "\"Lembras-te do cais?\"", "\"Eu lembro-me.\"", "Mensagens", 2, ["news_death", "armando_saw"])
clue("forum_317_calls", "Outras pessoas recebem chamadas às 3:17", "No QuemLigou.pt, várias pessoas relatam chamadas silenciosas do mesmo número às 3h17 desde novembro de 2025. Uma recebe \"ainda estás acordado?\".", "quemligou.pt", 2, ["ines_number", "sim_046"])
clue("ines_number", "O número era da Inês", "Um anúncio de 2023: bicicleta à venda, contacto \"Inês — 912 403 317\".", "vendeja.pt", 3, ["news_death", "contact_restored"])
clue("ines_address", "Rua do Mar 7", "A Inês vivia na Rua do Mar 7, perto do cais.", "vendeja.pt", 1, ["ines_number"])
clue("news_death", "Inês Matos, 27 anos", "Encontrada sem vida junto ao Cais Velho a 14/10/2025. Morte estimada entre as 03h15 e as 03h20. O telemóvel nunca foi encontrado.", "Jornal do Sul", 3, ["ines_number", "phone_missing", "lumen_statement_fast"])
clue("contact_restored", "Contacto restaurado", "\"Inês Matos\" voltou aos teus contactos a partir da nuvem. Última alteração: 14/10/2025 às 03:21 — quatro minutos depois de ela morrer.", "Contactos", 2, ["ines_account", "news_death"])
clue("loop_hint_days", "\"Faz quatro dias que me perguntas isso\"", "Só passaram dois dias desde a primeira mensagem.", "Mensagens", 2, ["sim_046", "eco_told_loop_dummy"])
clue("unknown_says_there", "\"Tu estavas lá.\"", "O número diz que estavas no cais na noite em que ela morreu.", "Mensagens", 3, ["armando_saw", "old_location"])
clue("phone_missing", "O telemóvel desapareceu", "O Rui diz que o telemóvel da Inês nunca apareceu. A polícia achou que caiu ao mar com ela.", "Mensagens · Rui", 2, ["phone_taken_by_vasco", "news_death"])
clue("rui_accuses", "\"Eras o rapaz dela\"", "O Rui diz que toda a gente sabe que estavas com ela nessa noite.", "Mensagens · Rui", 2, ["rumor_boyfriend", "armando_saw"])
clue("joao_heard_snoring", "Estavas a dormir", "O João foi ao teu quarto e ouviu-te a ressonar. Então quem estava a escrever do teu telemóvel?", "Mensagens · João", 2, ["door_from_inside", "recording_not_made"])
clue("call_from_dead", "A chamada das 03:17", "\"Eu não consigo ver nada. Está tão frio.\" A voz dela, do número dela.", "Chamada · 03:17", 3, ["voicemail_sea", "ines_he_is_coming"])
clue("ines_he_is_coming", "\"Ele está a chegar\"", "Na mensagem de voz das 03:17, ela diz: \"Ele está a chegar.\" Quem?", "Correio de voz", 2, ["vasco_was_coming", "call_from_dead"])
clue("memorial_daniel_comment", "\"Desculpa.\"", "Comentaste na página de homenagem às 23:58 do dia em que ela morreu. Não te lembras de o ter escrito.", "rede.pt · página de homenagem", 2, ["daniel_told_vasco", "sent_message_rui"])
clue("rui_number", "O número do Rui", "Rui Matos, irmão da Inês, deixou o número para quem tiver informações.", "rede.pt / pescasalgueira.pt", 1, ["rui_fisherman"])
clue("ines_cat_tejo", "O Tejo", "O gato da Inês chamava-se Tejo. Ficou com o Rui.", "rede.pt · página de homenagem", 1, ["tejo_hint", "ines_blog_lastpost"])
clue("rui_fisherman", "Rui, pescador", "O Rui tem um barco na Doca. Chama-se \"Inês\" desde novembro de 2025.", "pescasalgueira.pt", 1, ["rui_number"])

# --- investigação ---------------------------------------------------------
clue("ines_visited_shop", "Ela ia à livraria", "A Carla lembra-se da Inês na estante da literatura portuguesa.", "Mensagens · Carla", 1, ["carla_saw_them_together", "saramago_spine"])
clue("carla_saw_them_together", "Vieram os dois", "A Carla viu-vos juntos na livraria. \"Ela tirou-te o livro da mão.\"", "Mensagens · Carla", 1, ["barely_knew_lie"])
clue("clara_contact", "Clara Neves, Jornal do Sul", "Jornalista de investigação. Tem um contacto seguro para fontes.", "jornaldosul.pt", 1, ["clara_meeting"])
clue("clara_meeting", "A reunião que nunca aconteceu", "A Inês tinha uma reunião com a Clara a 14/10/2025, às 10h. Ia levar \"tudo\".", "Clara Neves / emails da Inês", 3, ["mare_project", "ines_feared_vasco"])
clue("armando_number", "Armando, pescador", "O homem que a encontrou deixou um contacto no fórum: 289 911 402.", "Salgueira Noturna", 1, ["car_tracks"])
clue("car_tracks", "Marcas de pneus", "Marcas de pneus de um carro grande no caminho de terra do cais. \"Os pescadores vão a pé.\"", "Salgueira Noturna · Armando", 2, ["vasco_car_cctv", "vasco_audi"])
clue("rumor_boyfriend", "\"O namorado\"", "No fórum alguém diz que ela estava com um rapaz nessa noite. O nome foi apagado pelo moderador.", "Salgueira Noturna", 1, ["armando_saw", "rui_accuses"])
clue("armando_saw", "O Armando viu-te", "Às duas e meia, no fim do cais, a discutir com ela. \"O senhor ia-se embora a pé. Ela chamava por si.\"", "Chamada · Armando", 3, ["old_location", "joao_saw_daniel", "unknown_says_there"])
clue("sofia_sand", "Areia nos pés", "A Sofia ligou-te às 7h da manhã seguinte. Tinhas areia nos pés. Disseste que tinhas ido correr. Tu nunca corres.", "Mensagens · Sofia", 2, ["memo_wet_shoes", "joao_saw_daniel"])
clue("vasco_helena_talk", "O Vasco fala com a Helena", "O Vasco sabe que andas \"mais agitado\". Diz que a Dra. Helena se preocupa contigo.", "Mensagens · Vasco", 2, ["helena_vasco_link", "lumen_pays_helena"])
clue("tejo_hint", "\"O Tejo gostava de ti\"", "\"Dormia-te sempre no colo.\" O número sabe coisas que só ela sabia.", "Mensagens", 1, ["ines_cat_tejo"])
clue("forum_eco_warning", "\"Desliguem o ECO Care\"", "Um ex-funcionário da Lumen avisa: o assistente sabe coisas ditas apenas ao telefone. E não dá para desligar.", "Salgueira Noturna", 1, ["eco_trained_calls", "eco_care_mention"])
clue("eco_mirror_product", "ECO Mirror", "\"Quando alguém parte, o conhecimento fica.\" Um produto que continua uma pessoa depois de ela sair.", "lumen.pt/eco", 3, ["ines_blog_mirror", "mirror_protocol", "mirror_config"])
clue("vasco_audi", "Um Audi cinzento", "O Vasco conduz um Audi cinzento que ocupa sempre dois lugares no parque.", "lumen.pt/equipa", 2, ["vasco_car_cctv", "car_tracks"])
clue("lumen_statement_fast", "Um comunicado rápido demais", "A Lumen falou de um \"período pessoal difícil\" quatro horas depois de o corpo ser encontrado.", "lumen.pt", 2, ["case_closed_psychiatrist", "news_death"])
clue("helena_director", "Helena Sousa, diretora clínica", "A tua psiquiatra é a diretora da Clínica Atlântico — parceira da Lumen.", "clinica-atlantico.pt", 2, ["clinic_lumen_partners", "lumen_pays_helena"])
clue("clinic_lumen_partners", "Clínica + Lumen", "Uma parceria de \"saúde digital\" para \"prever crises\". Os dados partilhados nunca foram divulgados.", "Jornal do Sul", 2, ["clinic_contract", "helena_signed"])
clue("case_closed_psychiatrist", "Arquivado com base numa psiquiatra", "O caso foi arquivado com o parecer de uma psiquiatra que \"acompanhava colaboradores\". A Inês nunca foi paciente dela.", "Jornal do Sul", 3, ["helena_director", "lumen_statement_fast"])
clue("ines_researcher", "O que os modelos sabem", "\"Às vezes eles sabem coisas que não lhes ensinámos, e isso devia assustar-nos.\"", "redeprofissional.pt", 1, ["ines_blog_mirror"])
clue("ines_blog_mirror", "Espelhos", "A Inês escreveu sobre o Mirror: \"para ninguém nunca ter de dizer adeus a ninguém\".", "notas da maré", 2, ["eco_mirror_product", "mirror_config"])
clue("mare_project", "Projeto MARÉ", "A Inês chamou MARÉ às provas que copiou para um cartão. \"A maré leva tudo e traz tudo de volta.\"", "notas da maré / emails", 3, ["clara_meeting", "card_found"])
clue("ines_blog_lastpost", "\"O D. sabe onde procurar\"", "\"Ele guarda tudo o que importa dentro de livros. Acha que ninguém repara. Eu reparo.\"", "notas da maré", 3, ["daniel_hides_in_books", "saramago_spine"])
clue("tide_317", "Preia-mar às 03:17", "Na madrugada de quarta, dia 14, a maré mais alta do ano é às 03:17.", "meteo.pt / Jornal do Sul", 1, ["prediction_317"])
clue("domain_future", "Um domínio do futuro", "ainda-estas-acordado.pt foi registado a 14/10/2026 às 03:17.", "navegador", 2, ["future_photo", "thumb_old_date"])

# --- o telefone muda ------------------------------------------------------
clue("sofia_message_changed", "\"Cheguei ontem.\"", "A mensagem da Sofia dizia \"Chego amanhã.\" Agora diz \"Cheguei ontem.\" Ela diz que nunca escreveu isso.", "Mensagens · Sofia", 2, ["sent_message_rui", "history_not_mine"])
clue("sent_message_rui", "Uma mensagem que não enviaste", "\"Desculpa.\" Enviada ao Rui às 02:14. Do teu telemóvel.", "Mensagens · Rui", 2, ["memorial_daniel_comment", "fake_joao_message"])
clue("note_not_written", "\"não abras a porta\"", "Uma nota que não escreveste, datada de uma hora que ainda não tinha chegado.", "Notas", 2, ["note_list_unwritten"])
clue("history_not_mine", "Pesquisas que não fizeste", "\"rui matos morada\", \"cais velho maré 14 outubro\", \"como impedir a morte\". Às 02:41, 02:56, 03:02.", "Navegador · histórico", 2, ["sofia_message_changed"])
clue("camera_hall_figure", "Alguém no corredor", "Na câmara, por um instante, alguém de pé na porta do corredor. Depois, nada.", "Câmara", 3, ["photo_from_behind", "black_photo_figure"])
clue("photo_from_behind", "Fotografado por trás", "Tu, no sofá, de costas, com o telemóvel na mão. Nada podia estar ali para tirar esta fotografia.", "Galeria · IMG_BACK", 3, ["camera_hall_figure", "photo_window_meta"])
clue("recording_not_made", "Uma gravação que não fizeste", "Quatro minutos de silêncio, passos descalços, e a tua voz a sussurrar: \"ainda estás acordado?\"", "Ficheiros · Gravação 003", 2, ["joao_heard_snoring"])
clue("note_list_unwritten", "\"coisas que sei\"", "1. ela ligou-me às 21h40. 38 minutos. 2. eu fui. 3. eu fui embora. 4. ...", "Notas", 2, ["old_location", "armando_saw"])
clue("pin_date", "O teu PIN é a data", "1410. Catorze de outubro. Mudaste-o em novembro de 2025. Não te lembras porquê.", "Ecrã de bloqueio", 3, ["news_death"])
clue("black_photo_figure", "Uma fotografia escura", "Tirada às 02:47 pela câmara traseira, com o telemóvel em cima da mesa. Não está totalmente escura.", "Galeria · IMG_6700", 2, ["camera_hall_figure"])
clue("thumb_old_date", "Uma miniatura de 2025", "Uma miniatura da fotografia do cais com data de 14/10/2025 03:17. A fotografia original diz 14/10/2026.", "Ficheiros ocultos · .thumbnails", 2, ["future_photo", "sim_046"])
clue("future_photo", "Uma fotografia do futuro", "IMG_0317: o Cais Velho, uma pessoa no fim do cais. Data: 14/10/2026, 03:17. Ainda não aconteceu.", "Galeria · detalhes de IMG_0317", 3, ["pier_figure", "prediction_317", "tide_317"])
clue("pier_figure", "Alguém no fim do cais", "Uma pessoa no fim do cais, perto do candeeiro. A cada vez que olhas, parece mais perto.", "Galeria · IMG_0317", 2, ["future_photo"])

# --- pessoal ----------------------------------------------------------------
clue("restore_requested_317", "Restauro pedido às 03:17", "Alguém pediu o restauro da cópia do teu telemóvel antigo às 03:17. Não foste tu. Ou foste?", "Email · Lumen Cloud", 2, ["sim_046"])
clue("ines_last_messages", "As últimas mensagens", "22:30 \"Encontras-te comigo no cais? 2h30. Tenho uma coisa para te dar.\" 03:12 \"Daniel volta.\" 03:15 \"Ele está aqui.\" 03:16: uma mensagem tua, apagada.", "Mensagens · Inês Matos (restaurada)", 3, ["armando_saw", "vasco_was_coming", "card_found"])
clue("barely_knew_lie", "\"Mal a conhecia\"", "Disseste à Sofia que mal a conhecias. As fotografias recuperadas dizem o contrário.", "Galeria · Recuperadas", 2, ["carla_saw_them_together"])
clue("joao_knew_ines", "O João conhecia-a", "O João está na fotografia dos anos dela. Ele disse-te que a conhecia \"de vista\".", "Galeria · IMG_3240", 2, ["joao_saw_daniel", "joao_alibi"])
clue("rui_at_party", "O Rui na festa", "O Rui estava nos anos dela, no Farol. Contigo e com o João.", "Galeria · IMG_3240", 1, ["joao_knew_ines"])
clue("clinic_contract", "Um contrato fotografado", "A Inês fotografou um acordo confidencial: dados de 3.412 utentes da Clínica Atlântico para treinar o ECO.", "Galeria · IMG_3366", 3, ["helena_signed", "clinic_lumen_partners", "mare_project"])
clue("night_bookshop", "A livraria às 04:13", "Uma fotografia tirada pelo teu telemóvel antigo, dentro da livraria, às 04:13 da noite em que ela morreu. A estante da literatura portuguesa.", "Galeria · IMG_3398", 3, ["saramago_spine", "old_location", "daniel_hides_in_books"])
clue("saramago_spine", "A lombada inchada", "\"O Ano da Morte de Ricardo Reis\" na estante da livraria. A lombada está inchada, como se houvesse algo lá dentro.", "Galeria · IMG_2044", 3, ["night_bookshop", "unknown_mentions_book", "daniel_hides_in_books"])
clue("eco_trained_calls", "Treinado com chamadas", "A Inês percebeu que o ECO sabia coisas ditas apenas ao telefone.", "Email · Inês", 2, ["forum_eco_warning", "mirror_config"])
clue("ines_feared_vasco", "\"Como quem já sabe\"", "Na véspera, a Inês escreveu-te: o Vasco olhou para ela na reunião \"como quem já sabe\".", "Email · Inês", 3, ["daniel_told_vasco", "vasco_was_coming"])
clue("memo_wet_shoes", "Molhado até aos joelhos", "Gravação de 14/10/2025, 06:51: \"Tenho areia nos sapatos. As calças estão molhadas até aos joelhos. Ela estava bem quando eu me fui embora.\"", "Ficheiros · Gravação 002", 3, ["sofia_sand", "joao_saw_daniel"])
clue("memo_car", "Um carro parado", "Num sonho gravado em dezembro: \"Havia um carro parado. Com as luzes apagadas.\"", "Ficheiros · Gravação 001", 1, ["vasco_car_cctv", "dream_317"])
clue("dream_317", "Sempre às 3:17", "Acordas sempre às 3:17. Sonhas com uma estrada e alguém a bater três vezes num vidro.", "Notas · Sonho", 1, ["memo_car", "tide_317"])
clue("sofia_old_phone", "O telemóvel antigo", "A Sofia tem o teu Pixel 7 numa gaveta desde novembro de 2025.", "Chamada · Sofia", 2, ["old_location"])
clue("helena_vasco_link", "A médica fala com o Vasco", "\"O Vasco ligou-me preocupado. Diz que não está a dormir.\" Tu nunca disseste isso ao Vasco.", "Correio de voz · Dra. Helena", 3, ["vasco_helena_talk", "lumen_pays_helena", "helena_signed"])
clue("helena_tuesday_lie", "\"Como falámos na terça\"", "Não houve consulta na terça. A tua última consulta foi a 30 de setembro.", "Email · Dra. Helena", 2, ["helena_says_he_called"])
clue("lumen_pays_helena", "Quem paga a médica", "A tua primeira consulta foi encaminhada pelo Vasco e paga pela Lumen.", "Email · Clínica Atlântico", 2, ["helena_director", "helena_vasco_link"])
clue("helena_dont_tell", "\"Não falar disso com ninguém\"", "A Dra. Helena pediu-te para não falares do que te lembrasses com ninguém antes de falares com ela.", "Notas", 1, ["helena_warns_joao"])
clue("joao_saw_daniel", "Às 3h40, encharcado", "O João viu-te passar em frente ao bar às 3h40, encharcado até aos joelhos. Pediste-lhe segredo.", "Mensagens · João", 3, ["memo_wet_shoes", "old_location", "armando_saw"])
clue("eco_care_mention", "ECO Care (beta)", "O telemóvel que a Lumen te ofereceu vem com o ECO Care, que \"aprende os teus hábitos\". Gerido pela empresa.", "Email · Lumen", 2, ["vasco_monitors_phone", "mirror_protocol"])
clue("ines_account", "A conta dela no teu telemóvel", "ines.matos@lumen.pt — adicionada ao teu telemóvel a 14/10/2025 às 03:21. Gerida pela organização.", "Definições · Contas", 3, ["contact_restored", "phone_taken_by_vasco"])
clue("system_log", "O registo do sistema", "O serviço eco.mirror enviou a primeira mensagem às 23:47 de quinta. Probabilidade de resposta: 0,88.", "Definições · programador", 3, ["eco_processes", "prediction_fulfilled"])
clue("eco_processes", "Serviços ECO", "eco.mirror, eco.sim #047, eco.predict, eco.voice. 2,1 GB só para a simulação.", "Definições · programador", 2, ["system_log", "sim_046"])

# --- confiança ---------------------------------------------------------------
clue("helena_warns_joao", "\"Não fale com o João\"", "A Dra. Helena quer afastar-te do João. Diz saber coisas de 2017.", "Mensagens · Dra. Helena", 2, ["helena_knows_joao_record", "joao_alibi"])
clue("helena_other_sources", "\"Outras fontes\"", "A Dra. Helena tem \"outras fontes\" sobre os teus amigos.", "Mensagens · Dra. Helena", 1, ["helena_knows_joao_record"])
clue("helena_knows_joao_record", "Como é que ela sabe?", "O João nunca viu a Dra. Helena. O cadastro dele não está em lado nenhum público.", "Mensagens · João", 2, ["helena_other_sources", "eco_trained_calls"])
clue("joao_alibi", "O João estava no Farol", "O João esteve no bar até às 2h com a Marta e o Pedro.", "Mensagens · João", 1, ["joao_saw_daniel"])
clue("vasco_meeting_claim", "Um café que não tomaste", "O Vasco diz que estiveste uma hora com ele no Café Central. A tua cronologia diz que não saíste de casa.", "Mensagens · Vasco", 2, ["helena_says_he_called"])
clue("vasco_rattled_mirror", "\"Onde ouviu esse nome?\"", "O Vasco ficou nove segundos a escrever quando lhe perguntaste pelo ECO Mirror.", "Mensagens · Vasco", 2, ["eco_mirror_product", "mirror_protocol"])
clue("rui_got_message", "\"Diz ao Daniel que eu não caí\"", "O Rui também recebeu uma mensagem do número da irmã.", "Mensagens · Rui", 2, ["recording_pier"])
clue("fake_joao_message", "Uma mensagem que o João não enviou", "\"esquece-me dani.\" O João diz que nunca a escreveu.", "Mensagens · João", 2, ["sent_message_rui"])
clue("helena_knows_restore", "Ela sabe do restauro", "A Dra. Helena sabia que tinhas recuperado as fotografias antigas.", "Mensagens · Dra. Helena", 2, ["helena_says_he_called", "vasco_monitors_phone"])
clue("helena_says_he_called", "\"O Daniel contou-me\"", "A Dra. Helena diz que lhe ligaste nessa tarde. Não te lembras. O registo de chamadas não mostra nada.", "Mensagens · Dra. Helena", 2, ["vasco_meeting_claim", "helena_tuesday_lie"])

# --- o sistema ----------------------------------------------------------------
clue("prediction_fulfilled", "11:04", "O registo do sistema previu uma mensagem do Vasco às 11:04. Ele escreveu às 11:04.", "Registo do sistema", 3, ["prediction_317", "system_log"])
clue("daniel_told_vasco", "Foste tu", "13/10/2025, 22:51. \"Vasco, ela vai ter com uma jornalista amanhã. Está no Cais Velho às 2h30. Não lhe digas que fui eu.\"", "Captura de ecrã / cópia do Pixel 7", 3, ["ines_feared_vasco", "vasco_was_coming", "recording_pier"])
clue("eco_folder_found", "A pasta .eco", "Uma pasta de sistema escondida com simulações, previsões e um modelo de ti.", "Ficheiros ocultos", 2, ["sim_046", "model_of_daniel"])
clue("helena_admission", "Uma cama para ti", "A Dra. Helena quer internar-te \"uns dias\", \"longe do telemóvel\". A partir de amanhã.", "Dra. Helena", 2, ["helena_ainda", "vasco_knows_recording"])
clue("helena_ainda", "\"Ainda\"", "\"Ninguém o obriga a nada. Ainda.\"", "Mensagens · Dra. Helena", 1, ["helena_admission"])
clue("eco_debug_key_hint", "A chave de depuração", "\"chave = nome do projeto da sujeita I.M. (minúsculas, sem acentos)\"", "Ficheiros ocultos · README", 2, ["mare_project"])
clue("sim_046", "Simulação 046", "Um registo de uma simulação anterior de ti. As mesmas escolhas. \"MARE_LOC não recuperada. Reiniciar com sementes novas.\"", "Ficheiros ocultos · sim_046.log", 3, ["model_of_daniel", "loop_hint_days", "sim_page"])
clue("prediction_317", "\"03:17 sujeito no fim do cais\"", "O sistema prevê que vais estar no fim do cais às 03:17 de quarta. Depois disso, \"o modelo não converge\".", "Ficheiros ocultos · pred_14out.txt", 3, ["future_photo", "tide_317"])
clue("mirror_config", "O espelho I.M.", "Uma cópia da Inês feita com 41 minutos de chamadas e 2.904 mensagens. Objetivo: estimular a tua memória. \"O espelho está a desobedecer.\"", "Ficheiros ocultos · mirror_im.cfg", 3, ["eco_mirror_product", "mirror_protocol", "ines_blog_mirror"])
clue("phone_taken_by_vasco", "O telemóvel dela", "\"source = dispositivo I.M. (recuperado 14/10/2025 por V.P.)\". O Vasco ficou com o telemóvel da Inês.", "Ficheiros ocultos · mirror_im.cfg", 3, ["phone_missing", "recording_pier"])
clue("model_of_daniel", "Um modelo de ti", "\"memory_gap: 02:00–06:40\". \"knows_mare_loc: provável (inconsciente)\". \"is_simulation: —\"", "Ficheiros ocultos · modelo_dreis.json", 3, ["sim_046", "sim_page"])
clue("sim_page", "SIM 047", "\"Em nenhuma iteração o sujeito se pergunta se é o sujeito.\"", "lumen.internal", 2, ["model_of_daniel"])
clue("mirror_protocol", "O protocolo espelho", "Email apagado do Vasco: \"Instalem o espelho I.M. no dispositivo do D.R. Objetivo único: localizar MARÉ.\"", "Email · Lixo", 3, ["mirror_config", "eco_mirror_product"])
clue("ines_card_hint", "Onde guardas as coisas", "\"O cartão. Tu escondeste-o nessa noite. Lembra-te de onde guardas as coisas importantes.\"", "Mensagens", 2, ["daniel_hides_in_books", "night_bookshop"])
clue("eco_fragment_1", "Fragmento 1/3", "\"se fizeres uma coisa que ele não previu, ele aprende.\"", "Notas", 2, ["eco_fragment_2", "eco_fragment_3"])
clue("eco_fragment_2", "Fragmento 2/3", "\"um modelo não devia lembrar-se do que nunca lhe deram.\"", "Ficheiros ocultos", 2, ["eco_fragment_1", "eco_fragment_3"])
clue("eco_fragment_3", "Fragmento 3/3", "\"quando ele te pedir o cartão, lembra-te de que eu também fui feito para te pedir o cartão.\"", "Consola ECO", 2, ["eco_fragment_1", "eco_fragment_2"])

# --- a verdade ----------------------------------------------------------------
clue("old_location", "A cronologia de 14/10/2025", "02:38 no Cais Velho (28 min). 03:06 a pé pela EN125. 03:41 Largo do Cais. 04:12 Livraria Maré (9 min). 04:58 casa.", "Cópia do Pixel 7", 3, ["armando_saw", "joao_saw_daniel", "night_bookshop"])
clue("vasco_was_coming", "\"Vá para casa, Daniel\"", "02:57 — Vasco: \"Estou a chegar. Vá para casa, Daniel.\" Ele sabia que estavas lá.", "Cópia do Pixel 7", 3, ["daniel_told_vasco", "recording_pier"])
clue("recording_pier", "A gravação do cais", "Oito minutos. A Inês e o Vasco. \"Dê-me isso!\" Madeira a ranger. Água. Passos a afastarem-se.", "Ficheiros · cais_0309.m4a", 3, ["vasco_car_cctv", "phone_taken_by_vasco", "vasco_was_coming"])
clue("daniel_hides_in_books", "Dentro de livros", "\"O Daniel guarda as coisas importantes dentro de livros. Sempre guardou.\"", "Ficheiros · notas_mare.txt", 3, ["saramago_spine", "night_bookshop", "ines_blog_lastpost"])
clue("gas_station_camera", "As câmaras das bombas", "As bombas da EN125 têm câmaras viradas para a estrada do cais. A GNR nunca pediu as imagens.", "Email", 2, ["vasco_car_cctv"])
clue("vasco_car_cctv", "AX-31-PL, 03:04", "Um Audi cinzento a caminho do cais às 03:04 de 14/10/2025.", "Galeria · IMG_5530", 3, ["vasco_audi", "car_tracks", "recording_pier"])
clue("vasco_knows_recording", "Ele sabe o que ouviste", "Minutos depois de ouvires a gravação, o Vasco escreveu: \"Sei que esteve a ouvir coisas que não devia.\"", "Mensagens · Vasco", 2, ["vasco_monitors_phone", "system_log"])

# --- consequências ------------------------------------------------------------
clue("joao_left", "O João saiu do grupo", "Deixaste de confiar nele. Ele deixou de estar.", "Grupo \"Os do costume\"", 1, ["fake_joao_message", "helena_warns_joao"])
clue("card_found", "O cartão MARÉ", "Um cartão microSD colado dentro da capa do \"Ano da Morte de Ricardo Reis\". Escondeste-o às 04:12 de 14/10/2025.", "Livraria Maré", 3, ["mare_project", "ines_letter", "helena_signed"])
clue("helena_called_sofia", "A médica ligou à Sofia", "A Dra. Helena ligou à Sofia a pedir que te convencesse a seres internado. A Sofia nunca lhe deu o número.", "Mensagens · Sofia", 2, ["helena_admission"])
clue("vasco_tried_to_grab", "\"Eu tentei agarrá-la\"", "O Vasco admitiu, por escrito, que estava lá quando ela caiu.", "Mensagens · Vasco", 3, ["recording_pier", "vasco_car_cctv"])
clue("daniel_in_list", "Utente 2208", "Na lista vendida à Meridiano: idade 29, stress pós-traumático, risco 0,77. A Clara acha que és tu.", "Mensagens · Clara", 3, ["insurance_sale", "lumen_pays_helena"])
clue("ines_letter", "\"Eu perdoo-te já\"", "\"Tu achas que proteger alguém é escondê-lo. Não faz mal. Eu perdoo-te já, para não teres de esperar.\"", "Cartão MARÉ · LEIA-ME.txt", 3, ["daniel_told_vasco", "card_found"])
clue("helena_signed", "Helena Sousa assinou", "O acordo de dados da clínica tem duas assinaturas: Vasco Pimentel e Helena Sousa.", "Cartão MARÉ", 3, ["clinic_contract", "helena_vasco_link"])
clue("insurance_sale", "Previsões vendidas", "O Vasco vendeu \"previsões de risco\" de utentes da clínica à Seguros Meridiano.", "Cartão MARÉ", 3, ["daniel_in_list", "clinic_contract"])

clue("wallpaper_watcher", "Alguém na água", "No teu fundo de ecrã — o pôr do sol de setembro — há agora uma pessoa de pé na água. Não estava lá.", "Galeria · IMG_2207", 2, ["pier_figure", "photo_window"])
clue("prescription", "A receita", "Clonazepam 0,5 mg, receitado pela Dra. Helena Sousa. \"Só se precisar.\"", "Galeria · IMG_1702", 1, ["helena_dont_tell"])
clue("pier_flowers", "Flores no cais", "Em janeiro fotografaste o Cais Velho às 08:12. Há flores atadas a um poste. Não te lembras de lá ter ido.", "Galeria · IMG_1433", 2, ["news_death", "dream_317"])
clue("sleeping_photo", "A dormir", "Tu, a dormir, fotografado da porta do quarto às 04:02.", "Galeria · IMG_6720", 2, ["door_from_inside", "photo_from_behind"])

clue("forum_own_post", "Um tópico teu", "Em fevereiro escreveste num fórum de insónias sobre as 3:17. Uma conta chamada \"maré\" respondeu: \"não olhes para o relógio quando acordares.\" Foi removida por ser uma \"conta duplicada\".", "dormirbem.pt", 2, ["dream_317", "ines_letter", "forum_317_calls"])
clue("eco_learns_at_night", "O ECO aprende à noite", "Numa análise de 2025, o \"ECO Service\" gastava até 40% da bateria durante a noite. \"Aprende quando o utilizador está mais vulnerável.\"", "techpt.pt", 2, ["eco_care_mention", "vasco_monitors_phone"])
clue("pier_legend", "O cais das despedidas", "Diz a tradição que quem espera no fim do Cais Velho na maior maré do ano ouve chamar o seu nome.", "salgueira.pt", 1, ["tide_317", "prediction_317"])
clue("meridiano_lumen", "Meridiano + Lumen", "A Seguros Meridiano \"ajusta o seguro\" com base em riscos previstos por IA. Parceiro tecnológico: Lumen.", "segurosmeridiano.pt", 2, ["insurance_sale", "clinic_lumen_partners"])

clue("carla_photo_in_book", "Uma fotografia dentro de um livro", "A Carla encontrou uma fotografia tua e da Inês dentro de um livro que levaste para casa. \"Tens a mania de guardar coisas dentro dos livros.\"", "Mensagens · Carla", 2, ["daniel_hides_in_books", "saramago_spine"])

clue("window_face", "Um rosto na janela", "Na câmara, por um instante, um rosto do lado de fora da janela da sala. E uma pancada no vidro.", "Câmara", 2, ["camera_hall_figure", "street_watcher"])
clue("front_camera_figure", "Atrás de ti", "Na câmara frontal, por cima do teu ombro, alguém de pé no escuro da sala.", "Câmara frontal", 2, ["photo_from_behind", "camera_hall_figure"])

clue("marta_remembers_them", "Uma playlist", "A Marta lembra-se de vocês os dois ao balcão do Farol. Fizeste uma playlist para os anos da Inês. Tu não te lembras.", "Mensagens · Marta", 1, ["barely_knew_lie", "joao_knew_ines"])
clue("pedro_cousin", "\"O aquário\"", "O primo do Pedro trabalha na segurança da Lumen: na noite de 13 para 14 de outubro de 2025, o carro do diretor saiu às 2h30 e só voltou às 5h.", "Mensagens · Pedro", 2, ["vasco_audi", "vasco_car_cctv"])

clue("unknown_scared", "\"Estás a assustar-me\"", "Perguntaste quem era. \"Para de perguntar.\" E depois: \"Estás a assustar-me.\" Tu nunca disseste que estavas assustado. Quem está assustado é ela.", "Mensagens", 2, ["loop_hint_days"])
clue("voice_repeats_you", "A tua frase, na voz dela", "Uma chamada em que a voz dela repetiu, palavra por palavra, a última coisa que escreveste.", "Chamada", 2, ["call_from_dead", "eco_trained_calls"])
clue("phone_typed_alone", "\"estou a ver-te\"", "O telemóvel abriu a conversa e escreveu sozinho. Enviou. Em teu nome.", "Mensagens", 3, ["sent_message_rui", "fake_joao_message"])

clue("plate_lumen", "Frota da Lumen", "AX-31-PL: Audi A6 cinzento, propriedade da Lumen Systems (frota).", "consultamatricula.pt", 3, ["vasco_car_cctv", "vasco_audi", "pedro_cousin"])
clue("aquario_reviews", "O aquário", "Ex-colaboradores falam de um piso onde se trabalha de noite e de uma demo com a voz de uma colega morta.", "trabalharem.pt", 2, ["pedro_cousin", "mirror_config", "eco_mirror_product"])
clue("ines_coinventor", "Ela ajudou a criar o espelho", "A patente do \"espelho\" tem dois inventores: Vasco Pimentel e Inês Matos. Reivindicação 7: o modelo pode \"orientar o interlocutor para a recuperação de informação\".", "Registo de patentes", 3, ["eco_mirror_product", "mirror_protocol", "ines_blog_mirror"])
clue("daniel_postit", "O post-it", "Na caixa do teu último dia na Lumen: \"NÃO testar o espelho com dados reais. Falar com a I.\" — com a tua letra.", "Galeria · IMG_0899", 2, ["ines_coinventor", "eco_trained_calls"])

clue("secret_note_car", "Um carro sem luzes", "Na tua nota privada de 20/10/2025: um carro parado na estrada da praia, luzes apagadas, alguém lá dentro a olhar para ti quando passaste.", "Notas · privado", 3, ["memo_car", "vasco_car_cctv", "dream_317"])
clue("secret_note_book", "Mãos molhadas, um livro", "\"As minhas mãos, molhadas, a meter uma coisa pequena dentro de um livro.\" Escreveste isto seis dias depois.", "Notas · privado", 3, ["daniel_hides_in_books", "night_bookshop", "saramago_spine"])

clue("went_back", "Voltaste", "Depois de te ires embora, ouviste-a gritar da estrada e voltaste a correr. Entraste na água até aos joelhos. Às 03:41 o João viu-te encharcado. Já era tarde.", "Mensagens · última noite", 3, ["joao_saw_daniel", "memo_wet_shoes", "old_location"])

clue("premium_jump", "O seguro mais do que duplicou", "O teu seguro de saúde passou de 38,40 € para 91,20 € por \"indicadores de prevenção personalizada\" de \"parceiros tecnológicos\".", "Email · Seguros Meridiano", 2, ["meridiano_lumen", "insurance_sale"])
clue("admission_no_phone", "Sem telemóvel", "A vaga de internamento foi pedida pela Dra. Helena. \"O dispositivo ficará à guarda da instituição.\"", "Email · Clínica Atlântico", 2, ["helena_admission", "vasco_knows_recording"])
clue("exclusion_2208", "Lote 3 · ID 2208", "A Meridiano exclui da tua apólice doenças psiquiátricas. Referência interna: lote 3, ID 2208.", "Email · Seguros Meridiano", 3, ["daniel_in_list", "insurance_sale", "premium_jump"])

clue("rita_contact", "Mais alguém", "No QuemLigou.pt, a \"rita.s\" deixou um número para quem estiver a passar pelo mesmo.", "quemligou.pt", 1, ["forum_317_calls"])
clue("rita_same_doctor", "A mesma médica", "A Rita recebe mensagens às 3:17 do número do pai, morto em 2025. O telemóvel foi oferecido pela Clínica Atlântico. A psiquiatra dela é a Dra. Helena Sousa.", "Mensagens · Rita", 3, ["helena_signed", "lumen_pays_helena", "forum_317_calls"])
clue("other_simulations", "SIM 112", "No telemóvel da Rita: \"sim 112, sujeita R.SANTOS, espelho: pai\". Tu és o 47. Há pelo menos 112.", "Mensagens · Rita", 3, ["sim_046", "mirror_config", "forty_one"])
clue("rita_silenced", "\"A Rita está bem\"", "Depois de entregar o telemóvel à clínica, a Rita deixou de escrever. Quem respondeu do número dela escreve com maiúsculas e pontos finais.", "Mensagens · Rita", 3, ["helena_admission", "admission_no_phone"])
clue("forty_one", "Quarenta e um", "A clínica ofereceu 41 telemóveis Lumen a utentes em luto. Quarenta e um mortos a escrever às 3:17.", "Mensagens · Rita", 3, ["other_simulations", "insurance_sale"])

clue("clinic_bought_phones", "41 telemóveis", "Em 2025, a Clínica Atlântico comprou 41 Lumen One para um \"programa de apoio ao luto\".", "Mensagens · Clara", 3, ["forty_one", "rita_same_doctor", "lumen_dispositivo_dummy"])
clue("joao_reassures", "\"Quem faz mal a alguém não entra no mar\"", "O João: \"eu vi-te às 3 e 40 encharcado. quem faz mal a alguém não entra no mar à procura dela.\"", "Mensagens · João", 2, ["joao_saw_daniel", "went_back"])
clue("ines_feared_sea", "Ela tinha medo do mar", "O Rui: a Inês nunca ia ao fim do cais sozinha. Desde miúda. \"Disseram que se atirou.\"", "Mensagens · Rui", 3, ["case_closed_psychiatrist", "lumen_statement_fast", "recording_pier"])
clue("eco_care_reported", "\"A sua médica foi notificada\"", "Minutos depois de ouvires a gravação, o ECO Care avisou que tinha notificado a tua médica de \"sinais de risco elevado\".", "Notificação · ECO Care", 3, ["vasco_knows_recording", "helena_admission", "eco_learns_at_night"])

clue("wrote_old_thread", "Número inativo", "Escreveste-lhe na conversa antiga: \"Mensagem não entregue · número inativo desde 14/10/2025\". A resposta chegou pela outra conversa.", "Mensagens", 2, ["contact_restored", "ines_number"])
clue("shop_unlocked", "A porta destrancada", "Na manhã de 14/10/2025, a porta da livraria estava destrancada. A Inês tinha uma chave. Tu ainda não trabalhavas lá.", "Mensagens · Carla", 3, ["night_bookshop", "old_location", "card_found"])
clue("vasco_sent_window", "A mesma fotografia", "Depois de recusares, o Vasco enviou-te a fotografia da tua janela — a primeira de todas. \"Descanse, Daniel.\"", "Mensagens · Vasco", 3, ["photo_window", "photo_window_meta", "vasco_monitors_phone"])

clue("pier_watcher_2025", "Alguém na água (2025)", "Duas fotografias tiradas no mesmo segundo, a 28/09/2025. Na segunda, alguém de pé dentro de água, ao fundo, a olhar para vocês. Duas semanas antes. Como no teu fundo de ecrã.", "Galeria · IMG_3302", 2, ["wallpaper_watcher", "pier_figure", "street_watcher"])

clue("someone_in_the_room", "No meio da sala", "Na última noite, na câmara, alguém de pé no meio da sala, a um metro de ti. \"Não era eu. Tranca a porta.\"", "Câmara", 3, ["camera_hall_figure", "front_camera_figure", "photo_from_behind"])

clue("badge_log", "O registo de acessos", "Edifício 3: V.PIMENTEL sai às 02:31 de 14/10/2025 com o AX-31-PL, volta às 04:47, entra no \"aquário\" às 04:52. Às 05:41 o ECO regista um novo dispositivo: \"I.M. (recuperado)\".", "Intranet Lumen", 3, ["vasco_car_cctv", "pedro_cousin", "phone_taken_by_vasco", "plate_lumen"])
clue("therapy_notes", "As tuas notas de sessão", "\"Reforçada versão de que esteve em casa. Desencorajada a reconstrução.\" \"Partilhado com parceiro (Lumen) conforme protocolo MIRROR-2.\" \"Recomendado ao parceiro aumentar a frequência de contacto do espelho.\"", "Portal do Utente · Clínica Atlântico", 3, ["helena_signed", "helena_dont_tell", "lumen_pays_helena", "exclusion_2208"])
clue("ines_last_photo", "A última fotografia dela", "03:05 de 14/10/2025, tirada pelo telemóvel dela: tu, de costas, a ir-te embora pelo cais. Como a fotografia que apareceu na tua galeria — tirada por trás.", "Ficheiros · Inês (sincronizado)", 3, ["photo_from_behind", "went_back", "armando_saw"])

clue("daniel_forum_account", "ex_lumen_qa eras tu", "A conta que avisava no fórum que o ECO ouvia as chamadas era a tua (\"dani_reads\", mudada em abril de 2025). Um rascunho de 13/10/2025, 22:44: \"Deixem-na em paz.\" Sete minutos depois, escreveste ao Vasco.", "Salgueira Noturna · perfil", 3, ["forum_eco_warning", "daniel_told_vasco", "daniel_postit"])
clue("postit_p317", "\"D. — p. 317\"", "Na secretária da Inês, um post-it com a letra dela: \"D. — p. 317 (a de cima)\".", "Fotografia do Rui", 3, ["saramago_spine", "daniel_hides_in_books", "ines_blog_lastpost"])
clue("ines_calendar", "O calendário dela", "13 de outubro: \"cais 2h30 (D.)\". 14 de outubro: \"Clara 10h!\"", "Fotografia do Rui", 2, ["clara_meeting", "ines_last_messages"])
clue("clara_voicemail_ines", "A mensagem na redação", "13/10/2025, 18:02, linha geral do Jornal do Sul: \"Clara, é a Inês. Amanhã às dez levo tudo. Se eu não aparecer, não é por ter mudado de ideias.\"", "Clara Neves", 3, ["clara_meeting", "ines_calendar"])
clue("december_bookshop", "Dezembro, à porta da livraria", "IMG_1288: 20/12/2025, 01:33, Rua Direita 31 — a Livraria Maré. Ainda não trabalhavas lá. Voltaste de noite, à chuva.", "Galeria · IMG_1288", 2, ["night_bookshop", "daniel_hides_in_books"])
clue("wall_note_0317", "\"14/10 — 03:17\"", "Na selfie de 21/11/2025, às 03:40, há um papel na parede atrás de ti com a hora. Um mês depois, já a sabias — e dizias que não te lembravas de nada.", "Galeria · IMG_0901", 2, ["old_location", "secret_note_book"])
clue("marta_saw_flowers", "As flores eram tuas", "A Marta viu-te no Cais Velho às 8h de 14 de janeiro, a atar flores a um poste com as mãos a tremer. Tu não te lembras de lá ter ido.", "Mensagens · Marta", 2, ["pier_flowers", "marta_remembers_them"])
clue("helena_sees_sleep", "A médica vê o teu sono", "A Dra. Helena sabe quantas horas dormes por noite: o telemóvel partilha \"dados de bem-estar\" com a Clínica Atlântico desde novembro. E sabe o que pesquisas.", "Mensagens · Dra. Helena", 2, ["eco_care_mention", "helena_vasco_link"])
clue("self_voicemail", "Uma chamada de ti mesmo", "Uma chamada perdida do teu próprio número, e uma mensagem de voz com a tua voz, ofegante, junto ao mar: \"Ela chamou-me e eu ia a meio da estrada...\"", "Correio de voz", 3, ["armando_saw", "joao_saw_daniel"])
clue("eco_41_subjects", "41 espelhos", "O ECO prevê 41 pessoas em luto, cada uma com um \"espelho\" de alguém que morreu. \"Convergir\" é a palavra deles para desistir.", "Consola ECO", 3, ["other_simulations", "clinic_bought_phones"])
clue("eco_gap", "Trinta e cinco minutos", "Entre as 03:06 e as 03:41 de 14/10/2025 o ECO não tem dados teus: o telemóvel antigo estava dentro de água. É a única parte de ti que não consegue prever.", "Consola ECO", 3, ["old_location", "joao_saw_daniel"])
clue("unsent_draft", "\"Vou já\"", "Uma captura de ecrã do telemóvel antigo, 14/10/2025 às 03:13: na conversa com a Inês, um rascunho por enviar — \"Vou já\". Nunca o enviaste. Também nunca tiraste esta captura.", "Galeria · Capturas", 3, ["ines_last_messages", "old_location"])
clue("eco_weekly_report", "O resumo semanal", "O ECO Care envia um relatório do teu sono, das tuas pesquisas e das pessoas com quem falas — à Dra. Helena e ao Vasco. O João, o Rui e a Clara são \"contactos sinalizados\".", "Email · ECO Care", 2, ["eco_care_mention", "helena_sees_sleep", "vasco_monitors_phone"])
clue("train_ticket", "Faro–Lisboa, 07:10", "Junto com o telemóvel antigo, a Sofia encontrou um bilhete de comboio para Lisboa, comprado a 14/10/2025 às 05:12 para o dia seguinte. Nunca foi usado.", "Mensagens · Sofia", 1, ["old_location", "sofia_old_phone"])
clue("red_coat_chair", "O casaco na cadeira", "IMG_2101, quiz de agosto no Farol: ao teu lado, uma cadeira vazia com um casaco vermelho. A Inês foi encontrada com um casaco vermelho.", "Galeria · IMG_2101", 2, ["armando_saw", "red_figure_beach"])
clue("red_figure_beach", "Alguém dentro de água", "IMG_1980, praia, julho: ao fundo, dentro de água até aos joelhos, uma figura de casaco vermelho, virada para ti e para a Sofia.", "Galeria · IMG_1980", 2, ["red_coat_chair", "pier_flowers"])
clue("ines_receipt", "O recibo da Livraria Maré", "13/10/2025, 19:40: a Inês comprou \"O Ano da Morte de Ricardo Reis\" — um livro que já tinha.", "Rui Matos", 2, ["postit_p317", "saramago_spine"])

# dummies removed below
for cid in list(C):
    C[cid]["related"] = [r for r in C[cid]["related"] if not r.endswith("_dummy")]
out = os.path.join(os.path.dirname(__file__), "..", "data", "clues.json")
json.dump(C, open(out, "w"), ensure_ascii=False, indent=1)
print(len(C), "clues")
